version: '2'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    ports:
     - ${APP_PORT}:80
    working_dir: /var/www/html
  cache:
    extends:
      file: docker-compose.base.yml
      service: cache
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    ports:
     - ${DB_PORT}:3306
  node:
    extends:
      file: docker-compose.base.yml
      service: node
    working_dir: /var/www/html
networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local
