version: '3'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    working_dir: /var/www/html
  cache:
    extends:
      file: docker-compose.base.yml
      service: cache
  node:
    extends:
      file: docker-compose.base.yml
      service: node
    working_dir: /var/www/html 
networks:
  appnet:
    driver: bridge
volumes:
  cachedata:
    driver: local
