#!/usr/bin/env bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

sed -i "s/AWS_ACCESS_KEY_ID/$1/g" $CURRENT_DIR/registry-config.yml
sed -i "s@AWS_SECRET_ACCESS_KEY@$2@g" $CURRENT_DIR/registry-config.yml # Note use of @ over /
sed -i "s/REGISTRY_BUCKET/$3/g" $CURRENT_DIR/registry-config.yml 
