version: 0.1
storage:
  s3:
    accesskey: AWS_ACCESS_KEY_ID
    secretkey: AWS_SECRET_ACCESS_KEY
    region: eu-central-1
    bucket: REGISTRY_BUCKET
    encrypt: true
    secure: true
    v4auth: true
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
http:
  addr: :5000
